application: friendsonnetflix
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

builtins:
- datastore_admin: on

handlers:
- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py

- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /static/(.*)
  static_files: static/\1
  upload: static/.*

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /.*
  script: main.py
